package com.pradeep.projecteuler;
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 */

public class Problem2 {

	public static void main(String[] args) {
		// System.out.println(fib(7));
		long i = 0;
		long a = 1;
		long b = 1;
		long sum = 0;
		long temp = 1;
		while (true) {
			if (temp >= 4000000)
				break;
			temp = a + b;
			a = b;
			b = temp;
			// System.out.println(temp);
			if (temp % 2 == 0)
				sum += temp;
		}
		System.out.println(sum);

	}

	public static long fib(long n) {
		if (n == 1 || n == 2)
			return 1;
		return fib(n - 1) + fib(n - 2);
	}

}
